# Generated by Django 5.0.6 on 2024-06-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='employee/')),
            ],
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
