# Generated by Django 5.0.6 on 2024-06-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_photo_delete_gender_remove_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee'),
            preserve_default=False,
        ),
    ]
